Allow byo custom  match configuration to determine customized output …
splunk/splunk-connect-for-kubernetes pull request #399
Opened 2020-05-25 02:55 UTC by limlengchye

…destination ( multiple indexes , hec-token etc )

## Proposed changes

Feature to allow user byo custom match configuration. 

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply._

- [x] I have read the [CONTRIBUTING](https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/CONTRIBUTING.md) doc
- [x] I have read the [CLA](https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/CLA.md)
- [x] I have added necessary documentation (if appropriate)
- [x] Any dependent changes have been merged and published in downstream modules

2021-07-26 20:34 UTC, rockb1017 commented
Thanks for contribution. You are adding custom match block after <match **>. so it will never get there. it should be placed before match **.

2021-07-26 20:38 UTC, rockb1017 requested changes

2021-07-26 20:38 UTC, rockb1017 commented on helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/templates/configMap.yaml
> +      # to use byo custom match conf
let change it to 
`# user custom match`

2021-07-26 20:38 UTC, rockb1017 commented on helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/templates/configMap.yaml
> +    {{ .Values.user_custom_match.conf | indent 4 }}
you may want to use `nindent` instead of `indent`. try it with some data.

2022-04-08 06:23 UTC, harshit-splunk commented
Closing the PR as it is inactive for a long time.

2022-04-08 06:23 UTC, closed without merging