Add PodAnnotations feature
splunk/splunk-connect-for-kubernetes pull request #578
Opened 2021-03-05 16:07 UTC by JonathanLachapelle

## Proposed changes

Pod annotations are not available for all deployment with splunk-connect, I added the possibility to set a pod annotations for all daemon set and deployment. This is very usefull if you have for instance istio and you want to disable the istio side-car injection.

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply._

- [X ] I have read the [CONTRIBUTING](https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/CONTRIBUTING.md) doc
- [X] I have read the [CLA](https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/CLA.md)
- [X] I have added necessary documentation (if appropriate)
- [X] Any dependent changes have been merged and published in downstream modules

2021-03-05 16:31 UTC, JonathanLachapelle commented
Anyone can re-run the build_test, it's not related to my changes.

2021-03-05 19:05 UTC, rockb1017 commented
re-running. I had to enable sharing environment variable. I recently added it for ruby version.

2021-04-23 20:13 UTC, rockb1017 requested changes
Could you also update the values.yaml file in the umbrella chart? `helm-chart/splunk-connect-for-kubernetes/values.yaml`

2021-04-23 20:13 UTC, rockb1017 commented on helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-objects/values.yaml
> +# Pod annotations for metrics daemonset
metrics -> objects

2021-07-13 23:22 UTC, merged