Spell Check in config values.yaml
splunk/splunk-connect-for-kubernetes pull request #649
Opened 2021-08-13 20:39 UTC by nhalstead

## Proposed changes

Documentation changes. Non-breaking.
This just corrects the spelling of some words in the `values.yaml` file.

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply._

- [x] I have read the [CONTRIBUTING](https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/CONTRIBUTING.md) doc
- [x] I have read the [CLA](https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/CLA.md)
- [x] I have added necessary documentation (if appropriate)
- [x] Any dependent changes have been merged and published in downstream modules

2021-08-16 07:39 UTC, sigbjornt commented on helm-chart/splunk-connect-for-kubernetes/values.yaml
> +# Splunk Connect for Kubernetes is a umbralla chart for three charts
Is it not "umbrella"

2021-08-16 22:36 UTC, rockb1017 commented on helm-chart/splunk-connect-for-kubernetes/values.yaml
> +# Splunk Connect for Kubernetes is a umbralla chart for three charts
Yea, please update. Thank you

2021-08-16 22:36 UTC, rockb1017 requested changes
Thank you. just one "umbrella" and others looks good!

2021-08-17 01:31 UTC, nhalstead commented on helm-chart/splunk-connect-for-kubernetes/values.yaml
> +# Splunk Connect for Kubernetes is a umbralla chart for three charts
FIxed.

2021-08-17 01:33 UTC, rockb1017 approved these changes

2021-08-17 06:49 UTC, merged