Allow custom labels on daemonset/deployment/pods
splunk/splunk-connect-for-kubernetes pull request #749
Opened 2022-03-22 22:14 UTC by alexanderldavis

## Proposed changes

This PR introduces a new variable to allow users to set their own custom labels on their deployments/daemonsets. 

Some organizations might have k8s admission controllers that require certain labels to be set, such as labels designating team/org ownership. This would enable such organizations to set the required labels.

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply._

- [X] I have read the [CONTRIBUTING](https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/CONTRIBUTING.md) doc
- [X] I have read the [CLA](https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/CLA.md)
- [X] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

2022-04-05 09:40 UTC, JAORMX submitted a review, later dismissed

2022-04-08 06:10 UTC, harshit-splunk requested changes
Thanks for fixing all the mistakes.
Only metric-aggr deployment is remaining. Can you also add extraLabels there?

2022-04-11 08:13 UTC, harshit-splunk commented
Since we are keeping separate config for metric and metricAggr, it would be better if we use `extraLabelsAggr`. What are your thoughts?

2022-04-12 02:51 UTC, alexanderldavis commented
> Since we are keeping separate config for metric and metricAggr, it would be better if we use `extraLabelsAggr`. What are your thoughts?

Agreed!

2022-04-13 12:17 UTC, harshit-splunk approved these changes
LGTM!

2022-04-13 12:17 UTC, merged