Add support for configuring namespaces
splunk/splunk-connect-for-kubernetes pull request #790
Opened 2022-07-18 17:31 UTC by FalconerTC

## Proposed changes

Currently, almost all resources being supplied by these charts are defaulting to `.Release.Namespace`. This is generally fine, but it's not configurable, and it doesn't support Gitops because `helm template` does not add `.Release.Namespace` for manifests (https://github.com/helm/helm/issues/3553). The result is that if you try to create the manifests and then apply them without using `helm install`, everything will be put in the `default` namespace

This makes `Namespace` explicit on all relevant resources.

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply._

- [ ] I have read the [CONTRIBUTING](https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/CONTRIBUTING.md) doc
- [ ] I have read the [CLA](https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/CLA.md)
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

2022-07-20 06:39 UTC, harshit-splunk commented
@FalconerTC can you fix failed tests?

2022-07-20 18:02 UTC, FalconerTC commented
@harshit-splunk I can't seem to get the e2e tests to work. Any advice here?

2022-07-29 06:04 UTC, harshit-splunk requested changes

2022-07-29 06:04 UTC, harshit-splunk commented on helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-objects/templates/configMap.yaml
> +  namespace: {{ template "splunk-kubernetes-objects.fullname" . }}
It should be `splunk-kubernetes-objects.namespace"`

2022-08-01 06:10 UTC, harshit-splunk approved these changes
LGTM!

2022-08-01 06:14 UTC, merged